- name: demo on prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: "Please enter the username"
      private: false

    - name: password
      prompt: "please enter the password"
      private: true

  tasks:
    - name: Check username validity
      fail:
        msg: "Access Denied! Incorrect username entered."
      when: username != "raghava"    

    - name: Check password validity
      fail:
        msg: "Access Denied! Incorrect password entered."
      when: password != "sirihari"
      no_log: true
    - name: print the information
      debug:
        msg: "username is: {{ username }}, password is : {{ password }}"
