- name: multiple packages are installing 
  hosts: ansiblenode
  become: yes
  tasks:

  - name: installing mulitple packages
    package:
     name: "{{ item }}"
     state: absent
    loop:
      - nginx
      - git
      - mysql


  