- name: user creation or check
  hosts: ansiblenode
  become: yes
  tasks:
  - name: check roboshop user is present or not
    command: id roboshop
    register: user_output
    ignore_errors: true
  - name: prit user_output
    debug:
      msg: "{{ user_output }}"
  - name: creating the user
    command: useradd roboshop
    when: user_output.rc != 0 