- name: user check
  hosts: ansiblenode
  become: yes
  tasks:
  - name: checking user
    command: id raghava
    register: user_output
    ignore_errors: true
  - name: print the user info
    debug: 
      msg: "{{ user_output }}"