- name: checking numbers
  hosts: local
  connection: local
  vars:
    given_number: 7
  tasks:
  when: given_number % 2 == 0
  debug:
    msg: "given number is :{{ given_number }} is even number"
- name: printing add
  debug:
    msg: "given number : {{ given_number }} is odd"
  when: given_number % 2 !=0